import type { INodePropertyOptions } from 'n8n-workflow';

const monthlyRevenueOptions: INodePropertyOptions[] = [
	{ name: 'Até 50 Mil', value: 'Até 50 mil' },
	{ name: 'De 1 À 4 Milhões', value: 'De 1 à 4 milhões' },
	{ name: 'De 101 Mil À 200 Mil', value: 'De 101 mil à 200 mil' },
	{ name: 'De 101 Mil À 400 Mil', value: 'De 101 mil à 400 mil' },
	{ name: 'De 16 À 40 Milhões', value: 'De 16 à 40 milhões' },
	{ name: 'De 201 Mil À 400 Mil', value: 'De 201 mil à 400 mil' },
	{ name: 'De 4 À 16 Milhões', value: 'De 4 à 16 milhões' },
	{ name: 'De 401 Mil À 1 Milhão', value: 'De 401 mil à 1 milhão' },
	{ name: 'De 51 Mil À 70 Mil', value: 'De 51 mil à 70 mil' },
	{ name: 'De 71 Mil À 100 Mil', value: 'De 71 mil à 100 mil' },
	{ name: 'From $101K to $200K', value: 'From $101K to $200K' },
	{ name: 'From $11K to $20K', value: 'From $11K to $20K' },
	{ name: 'From $16M to $40M', value: 'From $16M to $40M' },
	{ name: 'From $1M to $4M', value: 'From $1M to $4M' },
	{ name: 'From $201K to $400K', value: 'From $201K to $400K' },
	{ name: 'From $21K to $30K', value: 'From $21K to $30K' },
	{ name: 'From $31K to $40K', value: 'From $31K to $40K' },
	{ name: 'From $401K to $1M', value: 'From $401K to $1M' },
	{ name: 'From $41K to $50K', value: 'From $41K to $50K' },
	{ name: 'From $4M to $16M', value: 'From $4M to $16M' },
	{ name: 'From $51K to $70K', value: 'From $51K to $70K' },
	{ name: 'From $71K to $100K', value: 'From $71K to $100K' },
	{ name: 'Mais De 40 Milhões', value: 'Mais de 40 milhões' },
	{ name: 'More than $1M', value: 'More than $1M' },
	{ name: 'More than $40M', value: 'More than $40M' },
	{ name: 'Until $10K', value: 'Until $10K' },
];

const channelOriginOptions: INodePropertyOptions[] = [
	{ name: 'Acelerador Empresarial', value: 'Acelerador Empresarial' },
	{ name: 'Acelerador Experience', value: 'Acelerador Experience' },
	{ name: 'B Coorporate', value: 'B coorporate' },
	{ name: 'Bing', value: 'Bing' },
	{ name: 'Campanha De Recuperação', value: 'Campanha de Recuperação' },
	{ name: 'Embaixadores/Networking', value: 'Embaixadores/Networking' },
	{ name: 'Equity+', value: 'Equity+' },
	{ name: 'Escola Franchising', value: 'Escola Franchising' },
	{
		name: 'Eventos Em Parceria (Não Homologados Na Matriz)',
		value: 'Eventos em Parceria (não homologados na Matriz)',
	},
	{
		name: 'Eventos Independentes (Regionais/Locais)',
		value: 'Eventos Independentes (Regionais/Locais)',
	},
	{ name: 'Facebook', value: 'Facebook' },
	{ name: 'G4 Alumni', value: 'G4 Alumni' },
	{ name: 'G4 Gestão E Estratégia', value: 'G4 Gestão e Estratégia' },
	{ name: 'G4 Marketing E Growth', value: 'G4 Marketing e Growth' },
	{ name: 'G4 Sales', value: 'G4 Sales' },
	{ name: 'G4 Scale', value: 'G4 Scale' },
	{ name: 'G4 Traction', value: 'G4 Traction' },
	{ name: 'Gestão 4.0', value: 'Gestão 4.0' },
	{ name: 'Google', value: 'Google' },
	{ name: 'Goshen Land', value: 'Goshen Land' },
	{ name: 'Independente', value: 'Independente' },
	{ name: 'Indicação De Franqueado', value: 'Indicação de Franqueado' },
	{ name: 'Indicação de Investidor', value: 'Indicação de Investidor' },
	{ name: 'Indicação De Parceiro', value: 'Indicação de Parceiro' },
	{ name: 'Institucional', value: 'Institucional' },
	{ name: 'Jotaja', value: 'Jotaja' },
	{ name: 'LinkedIn', value: 'LinkedIn' },
	{ name: 'Lista De Leads Frios', value: 'Lista de Leads Frios' },
	{ name: 'Luminare', value: 'Luminare' },
	{ name: 'Multiplix', value: 'Multiplix' },
	{ name: 'Open Mind', value: 'Open Mind' },
	{ name: 'Orgânico', value: 'Orgânico' },
	{ name: 'Pinterest', value: 'Pinterest' },
	{ name: 'Programática', value: 'Programática' },
	{ name: 'Reativação', value: 'Reativação' },
	{ name: 'Recomendação BDR/SDR', value: 'Recomendação BDR/SDR' },
	{ name: 'Recomendação Closer', value: 'Recomendação Closer' },
	{ name: 'Reddit', value: 'Reddit' },
	{ name: 'RGV', value: 'RGV' },
	{ name: 'Scale', value: 'Scale' },
	{ name: 'Scale Company', value: 'Scale Company' },
	{ name: 'Scale Up', value: 'Scale Up' },
	{ name: 'Seja Ap', value: 'Seja Ap' },
	{ name: 'SME', value: 'SME' },
	{ name: 'Taboola', value: 'Taboola' },
	{ name: 'TikTok', value: 'TikTok' },
	{ name: 'Twitter', value: 'Twitter' },
	{ name: 'Vende C', value: 'Vende C' },
];

export const leadReasonOptions: INodePropertyOptions[] = [
	{ name: 'Adolescente/Criança', value: 'Adolescente/Criança' },
	{ name: 'Blocklist', value: 'Blocklist' },
	{ name: 'Cliente', value: 'Cliente' },
	{ name: 'Cliente Oculto', value: 'Cliente oculto' },
	{ name: 'Contatos Inválidos', value: 'Contatos inválidos' },
	{ name: 'Deixou De Responder', value: 'Deixou de responder' },
	{ name: 'Duplicado', value: 'Duplicado' },
	{ name: 'Engano/Não Lembra', value: 'Engano/Não Lembra' },
	{ name: 'Ex-Cliente (Detrator)', value: 'Ex-cliente (detrator)' },
	{ name: 'Não ICP', value: 'Não ICP' },
	{ name: 'Nunca Respondeu', value: 'Nunca respondeu' },
	{ name: 'Pessoa Física', value: 'Pessoa Física' },
	{ name: 'Sem Autoridade', value: 'Sem autoridade' },
	{ name: 'Sem Budget', value: 'Sem budget' },
	{ name: 'Sem Interesse', value: 'Sem interesse' },
	{ name: 'Sem Necessidade', value: 'Sem necessidade' },
	{ name: 'Sem Timing', value: 'Sem timing' },
	{ name: 'Serviço Fora De Escopo', value: 'Serviço fora de escopo' },
	{ name: 'SPAM', value: 'SPAM' },
];

export const leadCohortOptions: INodePropertyOptions[] = [
	{ name: 'CPG', value: 'CPG' },
	{ name: 'Education', value: 'Education' },
	{ name: 'Financial Services', value: 'Financial Services' },
	{ name: 'Food Service', value: 'Food Service' },
	{ name: 'Franchisee', value: 'Franchisee' },
	{ name: 'Outros', value: 'Outros' },
	{ name: 'Real State', value: 'Real State' },
	{ name: 'Retail', value: 'Retail' },
	{ name: 'Service B2B Multilocation', value: 'Service B2B Multilocation' },
	{ name: 'Service B2C Multilocation', value: 'Service B2C Multilocation' },
	{ name: 'Solar Energy / Electric Power', value: 'Solar Energy / Electric Power' },
	{ name: 'TELCO', value: 'TELCO' },
];

export const leadTemperatureOptions: INodePropertyOptions[] = [
	{ name: 'Quente', value: 'Quente' },
	{ name: 'Morno', value: 'Morno' },
	{ name: 'Frio', value: 'Frio' },
];

export const leadMeetingStatusOptions: INodePropertyOptions[] = [
	{ name: 'Falta Marcar', value: 'Falta marcar' },
	{ name: 'Falta Acontecer', value: 'Falta acontecer' },
	{ name: 'Aconteceu', value: 'Aconteceu' },
	{ name: 'No Show', value: 'No show' },
];

export const leadFirstDestinationOptions: INodePropertyOptions[] = [
	{ name: 'Blackbox', value: 'Blackbox' },
	{ name: 'LB', value: 'LB' },
	{ name: 'CRM', value: 'CRM' },
];

export const leadRevenueOptions: INodePropertyOptions[] = monthlyRevenueOptions;
export const leadLpRevenueOptions: INodePropertyOptions[] = monthlyRevenueOptions;

export const leadFoodSubnicheOptions: INodePropertyOptions[] = [
	{ name: 'Açaí E Sorvetes', value: 'Açaí e Sorvetes' },
	{ name: 'Comida Saudável', value: 'Comida Saudável' },
	{ name: 'Cozinha Internacional', value: 'Cozinha Internacional' },
	{ name: 'Culinária Japonesa', value: 'Culinária Japonesa' },
	{ name: 'Doces E Sobremesas', value: 'Doces e Sobremesas' },
	{ name: 'Lanchonete E Hamburgueria', value: 'Lanchonete e Hamburgueria' },
	{ name: 'Marmitaria E Comida Brasileira', value: 'Marmitaria e Comida Brasileira' },
	{ name: 'Pizzaria E Esfiharia', value: 'Pizzaria e Esfiharia' },
];

export const leadBrokerStatusOptions: INodePropertyOptions[] = [
	{ name: 'Black Box', value: 'Black Box' },
	{ name: 'Lead Comprado', value: 'Lead Comprado' },
	{ name: 'Lead Não Comprado', value: 'Lead Não Comprado' },
	{ name: 'Leilão', value: 'Leilão' },
	{ name: 'Não Leiloado', value: 'Não Leiloado' },
	{ name: 'Staage', value: 'Staage' },
];

export const leadSegmentOptions: INodePropertyOptions[] = [
	{ name: 'E-Commerce', value: 'E-commerce' },
	{ name: 'Educação', value: 'Educação' },
	{ name: 'Energia Solar', value: 'Energia Solar' },
	{ name: 'Finanças', value: 'Finanças' },
	{ name: 'Food Service', value: 'Food Service' },
	{ name: 'Franquia / Franchising', value: 'Franquia / Franchising' },
	{ name: 'Imobiliária', value: 'Imobiliária' },
	{ name: 'Indústria', value: 'Indústria' },
	{ name: 'Outro', value: 'Outro' },
	{ name: 'SAAS', value: 'SAAS' },
	{ name: 'Serviço', value: 'Serviço' },
	{ name: 'Telecom', value: 'Telecom' },
	{ name: 'Turismo', value: 'Turismo' },
	{ name: 'Varejo', value: 'Varejo' },
];

export const leadMarketingProductsOptions: INodePropertyOptions[] = [
	{ name: 'A Alavanca', value: 'A Alavanca' },
	{ name: 'Alavancagem Comercial', value: 'Alavancagem Comercial' },
	{ name: 'Assessoria', value: 'Assessoria' },
	{ name: 'Assessoria Recuperado Hyperflow', value: 'Assessoria Recuperado Hyperflow' },
	{ name: 'Auditoria Growth', value: 'Auditoria Growth' },
	{ name: 'Bday 2025', value: 'Bday 2025' },
	{ name: 'Blackbox', value: 'Blackbox' },
	{ name: 'Estruturação Estratégica', value: 'Estruturação Estratégica' },
	{ name: 'Gabarito De Recordes De Vendas', value: 'Gabarito de Recordes de Vendas' },
	{ name: 'Masterclass GdM', value: 'Masterclass GdM' },
	{ name: 'Material Rico', value: 'Material Rico' },
	{ name: 'Mentoria GT', value: 'Mentoria GT' },
	{ name: 'Mesa4X', value: 'Mesa4X' },
	{ name: 'MVP USA', value: 'MVP USA' },
	{ name: 'O Único Plano', value: 'O Único Plano' },
	{ name: 'ROI System', value: 'ROI System' },
	{ name: 'RPE', value: 'RPE' },
	{ name: 'Soluções Comerciais', value: 'Soluções Comerciais' },
	{ name: 'Treinamento Comercial', value: 'Treinamento Comercial' },
	{ name: 'V4 Food', value: 'V4 Food' },
	{ name: 'V4 Marketing', value: 'V4 Marketing' },
	{ name: 'Vender Gera Equity', value: 'Vender Gera Equity' },
];

export const leadAcquisitionChannelOptions: INodePropertyOptions[] = [
	{ name: 'ABM', value: 'ABM' },
	{ name: 'Blackbox', value: 'Blackbox' },
	{ name: 'Eventos', value: 'Eventos' },
	{ name: 'Food Box', value: 'Food Box' },
	{ name: 'Indicação', value: 'Indicação' },
	{ name: 'Inside Box', value: 'Inside Box' },
	{ name: 'Leadbroker', value: 'Leadbroker' },
	{ name: 'LP Franquia', value: 'LP Franquia' },
	{ name: 'LP Matriz', value: 'LP Matriz' },
	{ name: 'Meetingbroker', value: 'Meetingbroker' },
	{ name: 'Networking', value: 'Networking' },
	{ name: 'Pandora Box', value: 'Pandora Box' },
	{ name: 'Prospecção Fria', value: 'Prospecção Fria' },
	{ name: 'Reativação', value: 'Reativação' },
	{ name: 'Recomendação', value: 'Recomendação' },
	{ name: 'Reposição Inside Box', value: 'Reposição Inside Box' },
];

export const leadLeadSourceOptions: INodePropertyOptions[] = [
	{ name: 'Inside', value: 'Inside' },
	{ name: 'Outside', value: 'Outside' },
];

export const leadOpportunitySourceOptions: INodePropertyOptions[] = leadLeadSourceOptions;

export const leadOriginChannelOptions: INodePropertyOptions[] = channelOriginOptions;

export const leadBusinessModelOptions: INodePropertyOptions[] = [
	{ name: 'Aplicativo (PLG)', value: 'Aplicativo (PLG)' },
	{ name: 'E-Commerce', value: 'E-commerce' },
	{ name: 'Food Service', value: 'Food Service' },
	{ name: 'Infoproduto/Educação Perpétuo', value: 'Infoproduto/Educação Perpétuo' },
	{ name: 'Inside Sales', value: 'Inside Sales' },
	{ name: 'Lançamento', value: 'Lançamento' },
	{ name: 'PDV - Varejo/Retail', value: 'PDV - Varejo/Retail' },
];

export const leadBooleanFieldNames: string[] = [
	'arquivado',
	'e_sao',
	'sem_roteamento',
	'enviar_para_o_deal_broker',
	'csc',
	'csc_oportunidade',
];

export const leadDropdownFieldNames: string[] = [
	'razao_da_desqualificacao',
	'cohort',
	'temperatura',
	'status_da_reuniao',
	'primeiro_destino',
	'faturamento_mensal',
	'subnicho_v4_food',
	'status_leadbroker',
	'segmento',
	'produtos_marketing',
	'canal_de_aquisicao',
	'faturamento_da_lp',
	'fonte_do_lead',
	'fonte_da_oportunidade',
	'canal_de_origem',
	'modelo_de_negocios',
];

export const leadDateFieldNames: string[] = [
	'data_de_fechamento_estimada',
	'data_de_observacoes_do_bant',
	'data_de_cadastro',
];

export const leadDateTimeFieldNames: string[] = ['data_hora_da_reuniao'];

export const leadNumberFieldNames: string[] = ['valor_leadbroker'];

export const leadTextFieldNames: string[] = [
	'descricao_da_desqualificacao',
	'detalhes_da_qualificacao',
	'qualidade_da_reuniao',
	'justificativa',
	'descricao_feita_pelo_lead',
	'form_name',
	'page_name',
	'campaign_id',
	'adset_id',
	'ad_id',
	'fbclid',
	'gclid',
	'external_id',
	'session_id',
	'client_id',
	'fbp',
	'fbc',
	'session_number',
	'fb_lead_id',
	'id_de_resposta_do_formulario',
	'nome_da_campanha_de_email',
	'id_da_campanha_de_email',
	'ip_do_cadastro',
	'cargo',
	'urgencia',
	'franquia_csc',
	'franquia_csc_oportunidade',
	'id_franquia_csc',
	'observacoes',
	'id_franquia_oportunidade',
];

export const customFieldsOptions: INodePropertyOptions[] = [
	{ name: 'Ad ID', value: 'ad_id' },
	{ name: 'Adset ID', value: 'adset_id' },
	{ name: 'Arquivado', value: 'arquivado' },
	{ name: 'Campaign ID', value: 'campaign_id' },
	{ name: 'Canal De Aquisição', value: 'canal_de_aquisicao' },
	{ name: 'Canal De Origem', value: 'canal_de_origem' },
	{ name: 'Cargo', value: 'cargo' },
	{ name: 'Client ID', value: 'client_id' },
	{ name: 'Cohort', value: 'cohort' },
	{ name: 'CSC', value: 'csc' },
	{ name: 'CSC Oportunidade', value: 'csc_oportunidade' },
	{ name: 'Data De Cadastro', value: 'data_de_cadastro' },
	{ name: 'Data De Fechamento Estimada', value: 'data_de_fechamento_estimada' },
	{ name: 'Data De Observações Do BANT', value: 'data_de_observacoes_do_bant' },
	{ name: 'Data/hora Da Reunião', value: 'data_hora_da_reuniao' },
	{ name: 'Descrição Da Desqualificação', value: 'descricao_da_desqualificacao' },
	{ name: 'Descrição Feita Pelo Lead', value: 'descricao_feita_pelo_lead' },
	{ name: 'Detalhes Da Qualificação', value: 'detalhes_da_qualificacao' },
	{ name: 'É SAO', value: 'e_sao' },
	{ name: 'Enviar Para O Deal Broker', value: 'enviar_para_o_deal_broker' },
	{ name: 'External ID', value: 'external_id' },
	{ name: 'Faturamento Da LP', value: 'faturamento_da_lp' },
	{ name: 'Faturamento Mensal', value: 'faturamento_mensal' },
	{ name: 'FB Lead ID', value: 'fb_lead_id' },
	{ name: 'Fbc', value: 'fbc' },
	{ name: 'Fbclid', value: 'fbclid' },
	{ name: 'Fbp', value: 'fbp' },
	{ name: 'Fonte Da Oportunidade', value: 'fonte_da_oportunidade' },
	{ name: 'Fonte Do Lead', value: 'fonte_do_lead' },
	{ name: 'Form Name', value: 'form_name' },
	{ name: 'Franquia CSC', value: 'franquia_csc' },
	{ name: 'Franquia CSC Oportunidade', value: 'franquia_csc_oportunidade' },
	{ name: 'Gclid', value: 'gclid' },
	{ name: 'ID Da Campanha De Email', value: 'id_da_campanha_de_email' },
	{ name: 'ID De Resposta Do Formulário', value: 'id_de_resposta_do_formulario' },
	{ name: 'ID Franquia CSC', value: 'id_franquia_csc' },
	{ name: 'ID Franquia Oportunidade', value: 'id_franquia_oportunidade' },
	{ name: 'IP Do Cadastro', value: 'ip_do_cadastro' },
	{ name: 'Justificativa', value: 'justificativa' },
	{ name: 'Modelo De Negócios', value: 'modelo_de_negocios' },
	{ name: 'Nome Da Campanha De Email', value: 'nome_da_campanha_de_email' },
	{ name: 'Observações', value: 'observacoes' },
	{ name: 'Page Name', value: 'page_name' },
	{ name: 'Primeiro Destino', value: 'primeiro_destino' },
	{ name: 'Produtos Marketing', value: 'produtos_marketing' },
	{ name: 'Qualidade Da Reunião', value: 'qualidade_da_reuniao' },
	{ name: 'Razão Da Desqualificação', value: 'razao_da_desqualificacao' },
	{ name: 'Segmento', value: 'segmento' },
	{ name: 'Sem Roteamento', value: 'sem_roteamento' },
	{ name: 'Session ID', value: 'session_id' },
	{ name: 'Session Number', value: 'session_number' },
	{ name: 'Status Da Reunião', value: 'status_da_reuniao' },
	{ name: 'Status Leadbroker', value: 'status_leadbroker' },
	{ name: 'Subnicho V4 Food', value: 'subnicho_v4_food' },
	{ name: 'Temperatura', value: 'temperatura' },
	{ name: 'Urgência', value: 'urgencia' },
	{ name: 'Valor Leadbroker', value: 'valor_leadbroker' },
];
